### PR TITLE
Update hello_world.py

### PR DESCRIPTION
**Pull request by Bornm1**

### CODE REVIEW

**Comment by Bornm1** [comment]
@codelingobot capture

**Comment by Bornm1** [comment]
@CodeLingoBot capture

**Comment by Bornm1** [comment]
@codelingobot capture test run

**Comment by Bornm1** [comment]
@codelingobot capture Test Problem Conversation

**Comment by Bornm1** [comment]
@codelingobotstaging capture Test Problem Conversation

**Comment by Bornm1** [comment]
@stagingcodelingobot test

**Comment by Daanikus** [comment]
@stagingcodelingobot  capture

**Comment by Bornm1** [comment]
@stagingcodelingobot capture Test Title
write something lore ipsum

**Comment by Bornm1** [comment]
merge

**Pull request merged**
